name: flutter_workpieces
description: Workpieces official website
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


# coyy from https://medium.com/@javico2609/5-libraries-that-make-flutter-development-easier-and-faster-d51cee875c33
# 5 Libraries that make Flutter development easier and faster.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.2
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  fluro: ^2.0.3
  flutter_markdown: ^0.6.10 
  mailto: ^2.0.0 
  cache_image: ^1.0.5
  dio: ^4.0.6
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/etcd_image.png
    - assets/images/livegb_image.png
    - assets/markdown/markdown.md

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
